### ISSUE TITLE
GEXF Output

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/aut#103]
Right now, we export networks in CSV and GDF.

I think we should explore exporting to GEXF as it would play nicer with [Ryan's Sigma.js](http://sigmajs.org) format. GDF import into Gephi seems a bit wonky too.

For Gephi users, [recent CSV importer enhancements](https://gephi.wordpress.com/2017/09/26/gephi-0-9-2-a-new-csv-importer/) make having a native file format for them less important. The new importer is great.

**Comment by greebie** [comment]
Just to point out a use case for this tool.  Because Sigma.js is primarily a visualisation tool, it would be nice to have a Gexf output that includes a large number of attributes for the nodes and edges. 

For example, "x" & "y" attributes would offer default positions on a canvas, web archive attributes (.com vs .org), page rank or if we are feeling ambitious, some NER responses based on the text in the record. 

Edge examples would be less common, but one example might be urls found inside <head> vs those inside <body>.

In an ideal world, I would be able to build a node and edge data frame, filter via these kinds of values and output both to a gexf.  

If pyspark plays nicely with networkx or igraph, it would be nice to include some algorithm values like eigenvector centrality.  If not, we will have to settle for the Sparkx Scala library.

**Comment by ianmilligan1** [comment]
Thanks @greebie, so you think this might wait until #13 is implemented and come out of that nicely? Do you want me to assign this to you to take on once we have DataFrames implemented?

**Comment by greebie** [comment]
I think it would be worth it to check.  It is also related to the discussion about maintaining Scala vs Python code.

**Comment by ianmilligan1** [comment]
I'm circling back to this – now that it is clear that we'll be keeping the Scala version, I think it's  important to try to have GEXF output.

**Comment by ianmilligan1** [comment]
Closed with #137
