### ISSUE TITLE
Investigate Jupyter notebooks on Altiscale

### ISSUE THREAD

**Issue by lintool** [archivesunleashed/aut#37]
Guide here: https://documentation.altiscale.com/jupyter

**Comment by ianmilligan1** [comment]
I think @greebie has been looking into this, maybe once we're all up and running in Python on Altiscale we can circle back to this.

**Comment by ianmilligan1** [comment]
I've investigated it a bit – basically, we can do it, but there'd be localhost tunneling involved so it'd be just for internal purposes rather than anything we could work into production I think. I think Jupyter is great to prototype locally but I don't think we need to spend too many cycles to get it up on Altiscale. Happy if others disagree though.
